followup displays email which will be sent to authors
linuxfrorg/linuxfr.org pull request #308
Opened 2021-05-29 16:30 UTC by Trim

While updating the CSS, I noticed the padding around the content
were not removed for small screens in the redaction space.

It's fixed too.

See [suivi request](https://linuxfr.org/suivi/message-pour-relance-dans-l-espace-de-redaction#comment-1853867).

Example of rendering for followup form:

![relancer les rédacteurs](https://cloud.adorsaz.ch/index.php/s/yF7G4Q8x7f6YktT/download)

2021-06-27 14:45 UTC, Oumph requested changes

2021-06-27 14:45 UTC, Oumph commented on app/views/redaction/news/show.html.haml
> +      Vous pouvez envoyer un email de relance aux participants de cette dépêche
```suggestion
      Vous pouvez envoyer un courriel de relance aux participants de cette dépêche
```

2021-06-27 14:45 UTC, Oumph commented on app/views/redaction/news/show.html.haml
> +      N’hésitez pas à leur donner des précisions (date de sortie imminente, demande de précisions, etc.).
```suggestion
      N’hésitez pas à leur donner ou demander des précisions (date de sortie imminente, demande d’informations complémentaires, etc.).
```

2021-06-27 14:45 UTC, Oumph commented on app/views/redaction/news/show.html.haml
> +    %h2 Email de relance
```suggestion
    %h2 Courriel de relance
```

2021-06-27 14:45 UTC, Oumph commented on app/views/redaction/news/show.html.haml
> +        = text_area_tag :message, "L'équipe d'animation vous encourage à finaliser la dépêche.", rows: 10
```suggestion
        = text_area_tag :message, "L’équipe d’animation vous encourage à finaliser la dépêche.", rows: 10
```

2021-06-28 13:28 UTC, Trim reviewed
Thanks for the review, I've applied commits to apply requested changes.

2023-01-29 14:12 UTC, merged